import * as React from "react"

function SvgComponent(props) {
  return (
    <svg viewBox="0 0 24 24" width={18} height={18} {...props}>
      <path
        fill="#E1EDFF"
        d="M4,0.5C4,0.2,3.8,0,3.5,0S3,0.2,3,0.5V1H2C0.9,1,0,1.9,0,3v11c0,1.1,0.9,2,2,2h12c1.1,0,2-0.9,2-2V3
	c0-1.1-0.9-2-2-2h-1V0.5C13,0.2,12.8,0,12.5,0S12,0.2,12,0.5V1H4V0.5z M1,14V4h14v10c0,0.6-0.4,1-1,1H2C1.4,15,1,14.6,1,14z M8,7.5
	c1.7-1.7,5.8,1.3,0,5.1C2.2,8.8,6.3,5.8,8,7.5z"
      />
    </svg>
  );
}

export default SvgComponent

//material-ui calendar_today icon https://material.io/resources/icons/?icon=calendar_today&style=baseline
//component generated by svgr https://github.com/gregberge/svgr
